version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
